services:
  accounts:
    image: "thembatman/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankwave
  loans:
    image: "thembatman/loans:latest"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankwave
  cards:
    image: "thembatman/cards:latest"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankwave
networks:
  bankwave:
    driver: "bridge"