build:
  version: "2.0"

loans:
  message: "Welcome to Bankwave loans related QA APIs "
  contactDetails:
    name: "John Doe - QA Developer"
    email: "johnDoe@mail.com"
  onCallSupport:
    - (011) 123-4567
    - (011) 987-6543
